import { Injectable } from '@angular/core';

@Injectable({
  providedIn: 'root'
})
export class MensagensService {

  public SENHA_INVALIDA = 'SENHA INVÁLIDA';
  public FALHA_LOGIN = 'FALHA AO REALIZAR LOGIN, TENTE NOVAMENTE MAIS TARDE';
  public FALHA_DADOS_USUARIO = 'FALHA AO BUSCAR OS DADOS DO USUÁRIO, TENTE NOVAMENTE MAIS TARDE';
  public FALHA_CIDADE = 'FALHA AO BUSCAR AS CIDADES, TENTE NOVAMENTE MAIS TARDE';
  public FALHA_SALVAR_ENDERECO = 'FALHA AO SALVAR O ENDEREÇO, TENTE NOVAMENTE MAIS TARDE';
  public SALVO_SUCESSO = 'SALVO COM SUCESSO';
  public FALHA_ENDERECO = 'FALHA AO BUSCAR  OS ENDEREÇOS, TENTE NOVAMENTE MAIS TARDE';
  public FALHA_TIPO_USARIO = 'FALHA AO BUSCAR  OS TIPOS DE USUÁRIO, TENTE NOVAMENTE MAIS TARDE';
  public FALHA_SALVAR_USUARIO = 'FALHA AO SALVAR O USUÁRIO, TENTE NOVAMENTE MAIS TARDE';
  public SENHAS_DIFERENTES = 'SUA SENHA ESTÁ DIFERENTE, POR FAVOR VERIFIQUE';
  public FALHA_ESTADO = 'FALHA AO BUSCAR OS ESTADOS, TENTE NOVAMENTE MAIS TARDE';
  public FALHA_SALVAR_CIDADE = 'FALHA AO SALVAR A CIDADE, TENTE NOVAMENTE MAIS TARDE';
  public FALHA_ENTREGA = 'FALHA AO BUSCAR AS SUAS ENTREGAS, TENTE NOVAMENTE MAIS TARDE';
  public FALHA_PEGAR_ENTREGA = 'FALHA AO PEGAR A ENTREGA, TENTE NOVAMENTE MAIS TARDE';
  public FALHA_LARGAR_ENTREGA = 'FALHA AO LARGAR A ENTREGA, TENTE NOVAMENTE MAIS TARDE';
  public FALHA_EXCLUIR_ENTREGA = 'FALHA AO EXCLUIR A ENTREGA, TENTE NOVAMENTE MAIS TARDE';
  public FALHA_FINALIZAR_ENTREGA = 'FALHA AO FINALIZAR A ENTREGA, TENTE NOVAMENTE MAIS TARDE';

}
